version: '3.4'

services:
  lanre-func:
    image: ${DOCKER_REGISTRY-}lanre-func:${TAG:-latest}
    build:
      context: .
      dockerfile: Lanre.Func/Dockerfile
    environment:
    - AzureWebJobsStorage=
    - Storage=Development=
    - FUNCTIONS_WORKER_RUNTIME=dotnet
    ports:
    - "8080:80"