version: '3.4'

services:
  lanre-func:
    image: ${DOCKER_REGISTRY-}lanre-func:${TAG:-latest}
    build:
      context: .
      dockerfile: Lanre.Func/Dockerfile
    environment:
    - AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=lanrest;AccountKey=4q98FgrDNObwPuV+GpSIuvEexQPRjS+FH6gk7Ffqj232Ulp5BF6QWmvERr1cUjknnaxX8xfqdWZA4EyZ2cFFjg==;EndpointSuffix=core.windows.net
    - Storage=Development=DefaultEndpointsProtocol=https;AccountName=lanrest;AccountKey=4q98FgrDNObwPuV+GpSIuvEexQPRjS+FH6gk7Ffqj232Ulp5BF6QWmvERr1cUjknnaxX8xfqdWZA4EyZ2cFFjg==;EndpointSuffix=core.windows.net
    - FUNCTIONS_WORKER_RUNTIME=dotnet
    ports:
    - "8080:80"